export interface EmployeeItem {
    account_id:       number;
    account:          string;
    zone_id:          number;
    zone:             string;
    location_id:      number;
    location:         string;
    lpn_id:           number;
    lpn:              string;
    kardex_id:        number;
    kardex:           string;
    category_id:      number;
    category:         string;
    image:            string;
    product_id:       number;
    sku:              string;
    barcode:          string;
    description:      string;
    quantity:         number;
    weight:           number;
    length:           number;
    width:            number;
    height:           number;
    lot:              string;
    expire_date:      string;
    uom_id:           number;
    uom:              string;
    unit_value:       string;
  }